/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2016-06-14 19:39:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CustomerHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/tags/layout.tag", Long.valueOf(1465932689402L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      if (_jspx_meth_t_005flayout_005f0(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_t_005flayout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:layout
    org.apache.jsp.tag.web.layout_tag _jspx_th_t_005flayout_005f0 = (new org.apache.jsp.tag.web.layout_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_t_005flayout_005f0);
    _jspx_th_t_005flayout_005f0.setJspContext(_jspx_page_context);
    _jspx_th_t_005flayout_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_t_005flayout_005f0, null));
    _jspx_th_t_005flayout_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_t_005flayout_005f0);
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">   \r\n");
      out.write("\t$(function() {$( \"#move_in_date\" ).datepicker();}); \r\n");
      out.write("</script>\r\n");
      out.write("    <form method=\"post\" action=\"ApartmentSearch\">\r\n");
      out.write("    \t<div class=\"panel panel-default marginLeft marginRight\">\r\n");
      out.write("\t    \t<div class=\"panel-heading\">\r\n");
      out.write("\t    \t\tApartment Search\r\n");
      out.write("\t    \t</div>\r\n");
      out.write("\t    \t<div class=\"panel-body\">\r\n");
      out.write("\t    \t\t<dl class=\"dl-horizontal\">\r\n");
      out.write("\t    \t\t\t<dt>Move-in Date</dt>\r\n");
      out.write("\t    \t\t\t<dd>\r\n");
      out.write("\t    \t\t\t\t<div class='searchfield'><input class=\"form-control\" type=\"text\" name=\"move_in_date\" id=\"move_in_date\"/></div>\r\n");
      out.write("\t    \t\t\t</dd>\r\n");
      out.write("\t    \t\t\t<dt>Price Range</dt>\r\n");
      out.write("\t    \t\t\t<dd>\r\n");
      out.write("\t    \t\t\t\t<div class='searchfield'><input class=\"form-control price-range\" type=\"text\" name=\"price_range_low\" value=\"\" /> - <input class=\"form-control price-range\" type=\"text\" name=\"price_range_high\" value=\"\" /></div>\r\n");
      out.write("\t    \t\t\t</dd>\r\n");
      out.write("\t    \t\t\t<dt>Location</dt>\r\n");
      out.write("\t    \t\t\t<dd>\r\n");
      out.write("\t    \t\t\t\t<div class='searchfield'><input class=\"form-control\" type=\"text\" name=\"location\" value=\"\" /></div>\r\n");
      out.write("\t    \t\t\t</dd>\r\n");
      out.write("\t    \t\t\t<dt>Apartment Type</dt>\r\n");
      out.write("\t    \t\t\t<dd>\r\n");
      out.write("\t    \t\t\t\t<div class='searchfield'><select  class=\"form-control searchfield\" name=\"apartment_type\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"studio\">Studio</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1bd\">1 BD</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2bd\">2 BD</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3bd\">3 BD</option>\r\n");
      out.write("\t\t\t\t\t\t</select></div>\r\n");
      out.write("\t    \t\t\t</dd>\r\n");
      out.write("\t    \t\t</dl>\r\n");
      out.write("\t    \t</div>\r\n");
      out.write("\t    \t<div class=\"panel-footer clearfix\">\r\n");
      out.write("\t    \t\t<input class=\"btn btn-default pull-left\" type=\"reset\" value=\"Reset\" />\r\n");
      out.write("\t    \t\t<a class=\"btn btn-primary pull-right\" href=\"ApartmentSearchResults.jsp\"> Search </a>\r\n");
      out.write("\t    \t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </form>\r\n");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
